### ISSUE TITLE
Not working Server Sart Listening and than crash the Server Client.

### ISSUE THREAD

**Issue by rug4ever** [sbeuh34/NeoFlyMultiplayer#2]
Not working Server Sart Listening and than crash the Server Client.

**Comment by sbeuh34** [comment]
Don't understand the problem here. Please share more information. (screenshots or reproduction steps)

**Comment by rug4ever** [comment]
Hello,

I start the server and this is not szarting than i start again its Crash, and close the Programm. if is Touch the Button only one i can See the Server Adress and the Server Response Server is listenining but not szarting. the Client can not connect because the Server is Zero connect

**Comment by sbeuh34** [comment]
How do you know the server is not starting? Having the server is listening message means that the server is actually running fine. You just needs to wait for a client.
If you click again on startserver while the server is already running it leads to this exception. I need to catch this error. But what you're facing seems not to be a problem to me.

**Comment by sbeuh34** [comment]
the last release v1.0-beta3 avoid the program to get stuck when pressing startserver while a server is already running on this tcp port.
